set echo on;

whenever sqlerror continue;
drop index SHRINE_ONT_ACT.ACT_DEMO_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_DEMO_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_DX_10_9_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_DX_10_9_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_DX_ICD10_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_DX_ICD10_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_DX_ICD9_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_DX_ICD9_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_LAB_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_LAB_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_MED_ALPHA_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_MED_ALPHA_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_MED_VA_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_MED_VA_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_CPT_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_CPT_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_HCPCS_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_HCPCS_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_ICD10_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_ICD10_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_ICD9_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_PX_ICD9_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_VISIT_APPLIED_IDX ;
drop index SHRINE_ONT_ACT.ACT_VISIT_EXCLUDE_IDX ;
drop index SHRINE_ONT_ACT.ACT_MED_VA_fullname_IDX;
drop index SHRINE_ONT_ACT.ACT_MED_VA_hlevel_IDX;
drop index SHRINE_ONT_ACT.ACT_MED_ALPHA_fullname_IDX;
drop index SHRINE_ONT_ACT.ACT_MED_ALPHA_hlevel_IDX;
whenever sqlerror exit sql.sqlcode;


alter session set current_schema=shrine_ont_act;

CREATE INDEX ACT_DX_ICD10_EXCLUDE_IDX ON ACT_ICD10CM_DX_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_DX_ICD9_EXCLUDE_IDX ON ACT_ICD9CM_DX_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_LAB_EXCLUDE_IDX ON ACT_LOINC_LAB_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_MED_VA_EXCLUDE_IDX ON ACT_MED_VA_V2_092818(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_PX_CPT_EXCLUDE_IDX ON ACT_CPT_PX_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_PX_HCPCS_EXCLUDE_IDX ON ACT_HCPCS_PX_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_PX_ICD10_EXCLUDE_IDX ON ACT_ICD10PCS_PX_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_PX_ICD9_EXCLUDE_IDX ON ACT_ICD9CM_PX_2018AA(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_DEMO_EXCLUDE_IDX ON NCATS_DEMOGRAPHICS(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_DX_10_9_EXCLUDE_IDX ON NCATS_ICD10_ICD9_DX_V1(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_VISIT_EXCLUDE_IDX ON NCATS_VISIT_DETAILS(M_EXCLUSION_CD) PARALLEL 2;
CREATE INDEX ACT_MED_ALPHA_EXCLUDE_IDX ON ACT_MED_ALPHA_V2_121318(M_EXCLUSION_CD) PARALLEL 2;

CREATE INDEX ACT_DX_ICD10_APPLIED_IDX ON ACT_ICD10CM_DX_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_DX_ICD9_APPLIED_IDX ON ACT_ICD9CM_DX_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_LAB_APPLIED_IDX ON ACT_LOINC_LAB_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_MED_VA_APPLIED_IDX ON ACT_MED_VA_V2_092818(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_PX_CPT_APPLIED_IDX ON ACT_CPT_PX_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_PX_HCPCS_APPLIED_IDX ON ACT_HCPCS_PX_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_PX_ICD10_APPLIED_IDX ON ACT_ICD10PCS_PX_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_PX_ICD9_APPLIED_IDX ON ACT_ICD9CM_PX_2018AA(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_DEMO_APPLIED_IDX ON NCATS_DEMOGRAPHICS(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_DX_10_9_APPLIED_IDX ON NCATS_ICD10_ICD9_DX_V1(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_VISIT_APPLIED_IDX ON NCATS_VISIT_DETAILS(M_APPLIED_PATH) PARALLEL 2;
CREATE INDEX ACT_MED_ALPHA_APPLIED_IDX ON ACT_MED_ALPHA_V2_121318(M_APPLIED_PATH) PARALLEL 2;

CREATE INDEX ACT_MED_VA_fullname_IDX ON ACT_MED_VA_V2_092818(c_fullname) PARALLEL 2;
CREATE INDEX ACT_MED_VA_hlevel_IDX ON ACT_MED_VA_V2_092818(c_hlevel) PARALLEL 2;

CREATE INDEX ACT_MED_ALPHA_fullname_IDX ON ACT_MED_ALPHA_V2_121318(c_fullname) PARALLEL 2;
CREATE INDEX ACT_MED_ALPHA_hlevel_IDX ON ACT_MED_ALPHA_V2_121318(c_hlevel) PARALLEL 2;

exit;
